<?php
$_content = $this->getHomePageContent();
$_imageHelper = Mage::helper('ml_homepage/homepage_image');
?>
    <!--    --><?php //if($_content->getMainImageEnable()): ?>
<!--      --><?php //if($_content->getSlideImageEnable()):?>
<!--              --><?php //echo Mage::helper('cms')->getBlockTemplateProcessor()->filter( $_content->getSlideImage());?>
<!--      --><?php //else :?>
<!--        <div class="top-image-container">-->
<!--            <a href="--><?php //echo $_content->getMainImageUrl() ?><!--">-->
<!--                <div class="main-image"-->
<!--                     style="background-image: url(--><?php //echo $_imageHelper->init($_content,'main_image'); ?><!--)">-->
<!--                </div>-->
<!--            </a>-->
<!--            <a data-target="#text-block-1" class="next-arrow" title="Next Section">-->
<!--                <img src="--><?php //echo $this->getSkinUrl('images/White_Arrow_Large.png') ?><!--" alt=""/>-->
<!--            </a>-->
<!--        </div>-->
<!--      --><?php //endif;?>
<!--    --><?php //endif; ?>
<!---->
<!--    --><?php //if($_content->getData('promotion_list_enable')): ?>
<!--        <div class="promotion_list  white-background" id="promotion_list">-->
<!--            --><?php //echo $_content->getPromotionList(); ?>
<!--        </div>-->
<!--    --><?php //endif; ?>
</div>

<div class="block-home block-home-slider ">
    <?php if($_content->getId() == 1 && $_content->getData('flipbook_2_images') ): ?>
        <div class="flipbook-2-images">
            <?php echo $this->getFlipBookCarousel() ?>
        </div>
    <?php endif; ?>

    <?php if($_content->getId() == 2 && $_content->getData('flipbook_1_image') ): ?>
        <div class="flipbook-1-image">
            <?php echo $this->getFlipBookCarousel() ?>
        </div>
    <?php endif; ?>

    <?php if($_content->getId() == 4 && $_content->getData('flipbook_2_images') ): ?>
        <div class="flipbook-2-images">
            <?php echo $this->getFlipBookCarousel() ?>
        </div>
    <?php endif; ?>

    <?php if($_content->getId() == 3 && $_content->getData('video_enable') ): ?>
        <?php $videoUrl = Mage::helper('ml_homepage/homepage')->getFileBaseUrl() . $_content->getData('video') ?>

        <?php // DS-90 ?>
        <?php $hostedVideo = $_content->getData('hosted_video_url');?>
        <?php
        if (!empty($hostedVideo)) {
            ?>
            <div class="wrap-video">
                <iframe
                    src="<?php echo $hostedVideo;?>">
                </iframe>
            </div>
            <?php
            // END DS-90
        } else {
            ?>
            <video width="800" controls >
                <source src="<?php echo $videoUrl ?>" type="video/mp4">
            </video>
        <?php
        }
        ?>

    <?php endif; ?>

    <?php if($_content->getData('video_list_enable')): ?>
        <div class="video_list white-background">
            <?php echo $_content->getVideoList(); ?>
        </div>
    <?php endif; ?>

</div>

<div class="block-home ">
    <?php if($_content->getData('image_block_1_enable')): ?>
        <div class="image-block-1">
            <a href="<?php echo $_content->getData('image_block_1_url') ?>"><img src="<?php echo $_imageHelper->getImageBaseUrl().$_content->getData('image_block_1'); ?>" /></a>
        </div>
    <?php endif; ?>

    <?php if($_content->getData('client_complain_enable')): ?>
        <div class="client_complain white-background">
            <?php echo $_content->getClientComplain(); ?>
        </div>
    <?php endif; ?>
</div>

<div class="block-home block-home-galery ">
    <div class="white-background">
        <?php if($_content->getData('featured_products')): ?>
            <?php echo $this->getFeaturedProducts(); ?>
        <?php endif; ?>
    </div>

    <?php if($_content->getData('list_logo_enable')): ?>
        <div class="list_logo white-background">
            <?php echo $_content->getListLogo(); ?>
        </div>
    <?php endif; ?>
</div>


<div class="block-home">
    <?php if($_content->getData('image_block_2_enable')): ?>
       <div class="bot-image-container ">
           <a href="<?php echo $_content->getData('image_block_2_url') ?>">
               <div class="image-block-2"
                    style="background-image: url(<?php echo $_imageHelper->init($_content,'image_block_2'); ?>)">
               </div>
           </a>
        </div>
    <?php endif; ?>
</div>



<?php if($_content->getData('designer')): ?>
    <div class="designer-container  white-background">
        <div class="designer">
            <ul class="bxslider">
                <?php $designerList = $this->getDesigner(); ?>
                <?php $count = 1; ?>
                <?php foreach($designerList as $designer): ?>
                    <?php if( $count == 1): ?>
                        <li>
                        <ul class="designer-column">
                    <?php endif; ?>
                    <li><a href="<?php echo $designer['url'] ?>"><?php echo $designer['name'] ?></a></li>
                    <?php if( ($count % 5) == 0): ?>
                        </ul>
                        </li>
                        <li>
                        <ul>
                    <?php endif; ?>
                    <?php if( $count == count($designerList)): ?>
                        </ul>
                        </li>
                    <?php endif; ?>
                    <?php $count++ ?>
                <?php endforeach; ?>
            </ul>
        </div>
    </div>
<?php endif; ?>

<script>
    jQuery(document).ready(function(){
        jQuery('.bxslider-homepage').bxSlider({
            mode: 'fade',
            auto: true
        });
    });
</script>