<?php
$category_id = 10;
$_productCollection = Mage::getModel('catalog/category')->load($category_id)
                    ->getProductCollection()
                    ->addAttributeToSelect('*') // add all attributes - optional
                    ->addAttributeToFilter('status', 1) // enabled
                    ->addAttributeToFilter('visibility', 4); //visibility in catalog,search
$_productCollection->getSelect()->limit(5);
Mage::getModel('review/review')->appendSummary($_productCollection);

$_helper = $this->helper('catalog/output');
?>
<?php if(!$_productCollection->count()): ?>
    <p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
<?php else: ?>
    <div class="col-md-12 col-sm-12 col-xs-12 ">
        <div class="block">
            <h4 class="title_block">
                <span><?php echo $this->__('Women fashion');?></span>
            </h4>
            <?php $_iterator = 0; ?>
            <div class="block_content">
                <ul class="list-inline text-center vel-tab">
                    <li class="active"><a href="#producttab182738439category4" data-toggle="tab"><span></span>Tops</a></li>
                    <li><a href="#producttab182738439category8" data-toggle="tab"><span></span>Dresses</a></li>
                    <li><a href="#producttab182738439category20" data-toggle="tab"><span></span>Beachwear</a></li>
                    <li><a href="#producttab182738439category21" data-toggle="tab"><span></span>Accessories</a></li>
                </ul>
                <div id="product_tab_content">
                    <div class="product_tab_content tab-content">
                        <div class="tab-pane active">
                            <div class="row">

                                <div id="producttab182738439-category-4" class="product_list grid ">
                    <?php foreach ($_productCollection as $_product): ?>
                        <div class="item<?php if( ++$_iterator == sizeof($_productCollection) ): ?> last<?php endif; ?>">
                            <div class="ajax_block_product product_block">
                                <div class="product-container default clearfix">
                                    <?php // Product Image ?>
                                    <div class="left-block">
                                        <div class="product-image-container">
                                            <div class="vel-image-more" data-idproduct="25">
                                                <a href="<?php echo $_product->getProductUrl() ?>" data-fancybox-group="other-views" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>">
                                                    <img class="img-responsive" src="<?php echo $_product->getImageUrl(); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" itemprop="image" >
                                                </a>
                                            </div>
                                            <a class="product_img_link" href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" itemprop="url">
                                                <img class="img-responsive" src="<?php echo  $_product->getImageUrl()?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" itemprop="image">
                                            </a>
                                        </div>
                                        <a class="quick-view" href="<?php echo $_product->getProductUrl() ?>" title="Quick view">
                                            <i class="icon icon-eye-open"></i>
                                            <span>Quick view</span>
                                        </a>
                                    </div>
                                    <?php // Product description ?>
                                    <div class="right-block">
                                        <div class="f-fix">
                                            <?php $_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>
                                            <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped; ?>"><?php echo $_helper->productAttribute($_product, $_product->getName() , 'name'); ?></a></h2>
                                            <?php if($_product->getRatingSummary()): ?>
                                                <?php echo $this->getReviewsSummaryHtml($_product) ?>
                                            <?php endif; ?>
                                            <div class="content_price"> <?php echo $this->getPriceHtml($_product, true) ?></div>
                                            <p class="product-desc">
                                                <?php echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
                                            </p>
                                            <div class="functional-buttons clearfix">
                                                <?php if($_product->isSaleable()): ?>
                                                    <div class="addtocart"><a title="<?php echo $this->__('Add to Cart') ?>" class="ajax_add_to_cart_button" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></a></div>
                                                <?php else: ?>
                                                    <div class="addtocart"> <span><?php echo $this->__('Out of stock') ?></span></div>
                                                <?php endif; ?>
                                                <?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
                                                    <a href="<?php echo $_compareUrl ?>" class="add_to_compare"><?php echo $this->__('Compare') ?></a>
                                                <?php endif; ?>
                                                <?php if ($this->helper('wishlist')->isAllow()) : ?>
                                                    <a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="addToWishlist"><?php echo $this->__('Wishlist') ?></a>
                                                <?php endif; ?>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    <?php endforeach; ?>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <script type="text/javascript">decorateList('products-list', 'none-recursive')</script>
    </div>
<?php endif; ?>
<script type="text/javascript">
    jQuery(document).ready(function() {
//        jQuery('#producttab182738439-category-4').owlCarousel({
//            items:1,
//            loop:true,
//            autoWidth:true,
//            stagePadding: 100,
//            navigation:true
//        });

        jQuery('.quick-view').click(function(e){
            e.preventDefault();
            var url = jQuery(this).attr('href');
            if (url.indexOf('?') != -1)
                url += '&';
            else
                url += '?';
            jQuery.fancybox({
                'padding':  0,
                'width':    1087,
                'height':   610,
                'type':     'iframe',
                'href':     url + 'content_only=1'
            });
        });

    });
</script>
