
<?php
$display_from_date = Mage::getStoreConfig("countdown/date_promotions/from_date");

$display_to_date = Mage::getStoreConfig("countdown/date_promotions/to_date");
//if (!empty($display_from_date) && !empty($display_to_date)) {
//    $date_convert = DateTime::createFromFormat('d/m/Y', $display_to_date);
//    $display_to_date_convert =  $date_convert->format('Y/m/d');
//    $date_convert = DateTime::createFromFormat('d/m/Y', $display_from_date);
//    $display_from_date_convert = $date_convert->format('Y/m/d');
//}

//========== config in admin : date display christmas promotions popup
$display_date = Mage::getModel('core/date')->date('Y-m-d');
$three_day_ago = Mage::getModel('core/date')->date('Y-m-d', strtotime('-3 day'));
$three_day_feature = Mage::getModel('core/date')->date('Y-m-d', strtotime('+3 day'));
$before_one_day = Mage::getModel('core/date')->date('Y-m-d', strtotime('-1 day'));
$after_one_day = Mage::getModel('core/date')->date('Y-m-d', strtotime('+1 day'));

//========= date for filter collection christmas products.
$date = strtotime($display_to_date); // count to christmas
//var_dump($display_date); die();
//========== date for count down
if( !empty($display_from_date) && !empty($display_to_date) &&
    strtotime($display_from_date) <= strtotime($display_date)
    && strtotime($display_date) <= strtotime($display_to_date)) {
//============ display popup from $display_from_date to $display_to_date.
?>
<div id="christmas-promotion-popup" class="count-down-christmas-promo" style="display: none">
<?php    if($date){
        $year = date("Y",$date);
        $month = date("m",$date);
        $day = date("d",$date);
        $hour = date("H",$date);
        $minute = date("i",$date);
        ?>
        <div class="christmas-promotions">
        <img class="aldi-christmas-promo-logo" src="/images/christmas-logo.png" alt="christmas logo">
        <div class="christmas-promotions-top">
            <div class="text-top-christmas">
                <h3 class="top-deals"><?php echo $this->__('18 Deals');?></h3>
                <h2 class="text-of-christmast"><?php echo $this->__('Of Christmas');?></h2>
            </div>
            <div class="count-down">
                <script type="text/javascript">
                    var Countdown<?php echo rand(100,999); ?> = new Countdown({
                        year	: <?php echo $year; ?>,
                        month	: <?php echo $month; ?>,
                        day	: <?php echo $day; ?>,
                        hour	: <?php echo $hour; ?>,
                        minute	: <?php echo $minute; ?>,
                        second	: 0,
                        width:'450',
                        height:'100',
                        color	: "#FFFFFF",
                        style:"flip",
                        rangeHi: "day"
                    });
                </script>
            </div>
            <div class="text-above-countdown">
                <h4><?php echo $this->__('Till Christmas');?></h4>
            </div>
        </div>
    <?php } ?>
    <?php $checkDate = null;$checkDate2 = null;$checkDate3 = null;
    $currency = Mage::app()->getLocale()->currency(Mage::app()->getStore()->getCurrentCurrencyCode())->getSymbol();
    ?>
    <?php
    $_products_three_day_before = Mage::getModel('catalog/product')->getCollection()
        ->addFieldToFilter('countdown_promo',array('lteq'=>$before_one_day))
        ->addAttributeToSort('countdown_promo', 'asc')
        ->addAttributeToSelect('image');
    if(strtotime($display_from_date_convert)> strtotime($three_day_ago))
        $_products_three_day_before->addFieldToFilter('countdown_promo',array('gteq'=>$display_from_date_convert));
    else
        $_products_three_day_before->addFieldToFilter('countdown_promo',array('gteq'=>$three_day_ago));
    $_products_current = Mage::getModel('catalog/product')->getCollection()
        ->addFieldToFilter('countdown_promo',array('eq'=>$display_date))
        ->addAttributeToSelect('brand')
        ->addAttributeToSelect('name')
        ->addAttributeToSelect('price')
        ->addAttributeToSelect('image');
    $_products_three_day_after = Mage::getModel('catalog/product')->getCollection()
        ->addFieldToFilter('countdown_promo',array('gteq'=>$after_one_day))
        ->addAttributeToSort('countdown_promo', 'asc');
    if(strtotime($display_to_date_convert) > strtotime($three_day_feature))
        $_products_three_day_after->addFieldToFilter('countdown_promo',array('lteq'=>$three_day_feature));
    else
        $_products_three_day_after->addFieldToFilter('countdown_promo',array('lteq'=>$display_to_date_convert));

    ?>
    <div class="widget widget-christmas-products">
        <div class="widget-products-christmas-promotions">
<!--            <ul class="christmas-product-list-ago">-->
<!--                --><?php //foreach ($_products_three_day_before as $_product): ?>
<!--                    --><?php //if(strtotime($checkDate) != strtotime($_product->getChristmasPromo())):?>
<!--                        <li class="item" >-->
<!--                            --><?php //$_product = Mage::getModel('catalog/product')->load($_product->getId()); ?>
<!--                            <div class="aldigridproductouterbox">-->
<!--                                <div class="image-box-christmas">-->
<!--                                    <a href="--><?php //echo $_product->getProductUrl() ?><!--" title="--><?php //echo $this->stripTags($_product->getName(), null, true) ?><!--" class="product-image">-->
<!--                                        <img src="--><?php //echo $this->helper('catalog/image')->init($_product, 'image')->constrainOnly(TRUE)->keepAspectRatio(TRUE)->keepFrame(FALSE)->resize(100,125); ?><!--" width="100" height="100" alt="--><?php //echo $this->stripTags($_product->getName(), null, true) ?><!--" />-->
<!--                                    </a>-->
<!--                                </div>-->
<!--                                <div class="date-christmas">-->
<!--                                    <a href="--><?php //echo $_product->getProductUrl() ?><!--" title="--><?php //echo $this->stripTags($_product->getName(), null, true) ?><!--" class="product-image">-->
<!--                                        --><?php //echo date('d', strtotime($_product->getChristmasPromo()));?>
<!--                                    </a>-->
<!--                                </div>-->
<!--                            </div>-->
<!--                        </li>-->
<!--                        --><?php //$checkDate = $_product->getChristmasPromo(); ?>
<!--                    --><?php //endif;?>
<!--                --><?php //endforeach;?>
<!--            </ul>-->
            <ul class="christmas-product-current">
                <?php foreach ($_products_current as $_product): ?>
<!--                    --><?php //if(strtotime($checkDate2) != strtotime($_product->getChristmasPromo())):?>
                        <li class="item" >
                            <?php $_product = Mage::getModel('catalog/product')->load($_product->getId()); ?>
                            <div class="aldigridproductouterbox">
                                <div class="image-box-christmas">
                                    <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>" class="product-image">
                                        <img src="<?php echo $this->helper('catalog/image')->init($_product, 'image')->constrainOnly(TRUE)->keepAspectRatio(TRUE)->keepFrame(FALSE)->resize(326); ?>" width="100" height="100" alt="<?php echo $this->stripTags($_product->getName(), null, true) ?>" />
                                    </a>
                                </div>
                                <div class="product-price-current-date">
                                    <?php $price = floatval($_product->getPrice());
                                    list($whole, $decimal) = explode('.', $price);
                                    if($decimal==0) $decimal ='00';
                                    ?>
                                    <span><span class="price-current"><?php echo $currency.$whole;?></span><sup><?php echo '.'.$decimal;?></sup></span>

                                </div>
                                <div class="christmas-buynow">
                                    <a href="<?php echo $_product->getProductUrl(); ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>" class="product-image">
                                        <span><?php echo $this->__('Buy Now');?></span>
                                    </a>
                                </div>
                                <div class="christmas-detail-product">
                                    <h3 class="product-name">
                                        <a href="<?php echo $_product->getProductUrl() ?>"
                                           title="<?php echo $this->stripTags($_product->getName(), null, true) ?>">
                                            <?php echo $_product->getName();?>
                                        </a>
                                    </h3>
                                </div>
<!--                                <div class="date-christmas">-->
<!--                                    <span>--><?php //echo $this->__('Day');?><!--</span>-->
<!--                                    <span>--><?php //echo date('d', strtotime($_product->getCountdownPromo()));?><!--</span>-->
<!--                                </div>-->
                            </div>
                        </li>
<!--                        --><?php //$checkDate2 = $_product->getChristmasPromo(); ?>
<!--                    --><?php //endif;?>
                <?php endforeach;?>
            </ul>
<!--            <ul class="christmas-product-list-feature">-->
<!--                --><?php //foreach ($_products_three_day_after as $_product): ?>
<!--                    --><?php //if(strtotime($checkDate3) != strtotime($_product->getChristmasPromo())):?>
<!--                        <li class="item --><?php
//                        if(strtotime($_product->getChristmasPromo()) == strtotime($after_one_day)){
//                            echo 'tomorrow';
//                        }
//                        else {echo strtolower(date('l', strtotime($_product->getChristmasPromo())));}
//                        ?><!--" >-->
<!--                            <div class="aldigridproductouterbox">-->
<!---->
<!--                                <div class="date-christmas">-->
<!--                                    --><?php //echo date('d', strtotime($_product->getChristmasPromo()));?>
<!--                                </div>-->
<!--                                --><?php //if(strtotime($_product->getChristmasPromo()) == strtotime($after_one_day)):?><!--  <div class="day-of-product-feature"> --><?php //echo $this->__('Tomorrow');?><!--</div>-->
<!--                                --><?php //else:?>
<!--                                    <div class="day-of-product-feature">--><?php //echo date('l', strtotime($_product->getChristmasPromo()));?><!--</div>-->
<!--                                --><?php //endif;?>
<!--                            </div>-->
<!--                        </li>-->
<!--                        --><?php //$checkDate3 = $_product->getChristmasPromo(); ?>
<!--                    --><?php //endif;?>
<!--                --><?php //endforeach;?>
<!--            </ul>-->
        </div>
    </div>
    <div class="footer-the-perfect"><img src="<?php echo $this->getSkinUrl('images/the-perfect-text.png');?>" alt="footer-promo-perfect"/></div>
    </div>

    <script type="text/javascript">

        if(!Mage.Cookies.get('christmas')){
            // cookie not set
            Mage.Cookies.set('christmas', 'now');
            var show = true;
            //console.log('setting cookie : '+show);
        }else{
            ///cookie is set!
            var show = false;
        }
        //});

    </script>
    <script type="text/javascript">
        function getQueryParams(qs) {
            qs = qs.split("+").join(" ");
            var params = {},
                tokens,
                re = /[?&]?([^=]+)=([^&]*)/g;

            while (tokens = re.exec(qs)) {
                params[decodeURIComponent(tokens[1])] = decodeURIComponent(tokens[2]);
            }

            return params;
        }

        var $_GET = getQueryParams(document.location.search);

        jQuery(document).ready(function(){
            var loaded = false;
            if( jQuery(window).width() < 1200) var width = '100%';
            else if( jQuery(window).width()> 1899) var  width = '51,9%';
            else var width = '72%';
           // if(show || $_GET['christmas']){
                jQuery("#click-christmas-popup").fancybox({
                    padding: 0,
                    hideOnContentClick: true,
                    closeBtn : true,
                    autoCenter: false,
                    autoSize: false,
                    width: '960px',
                    openEffect  : 'none',
                    afterLoad: function () {
                        jQuery(".fancybox-wrap").addClass("christmas-promotions-content");
                    },
                    onUpdate: function() {
                        leftVal = jQuery( window ).width() - jQuery(".fancybox-wrap").width();
                        leftVal = leftVal/2;
                        jQuery(".fancybox-wrap").css('left', leftVal + 'px');
                    },
                    closeEffect : 'none'
                });
         //   }
            jQuery("#click-christmas-popup").trigger('click');

        });

    </script>
    <style>
        .christmas-product-list-feature .tomorrow .day-of-product-feature {
            background-image:url(<?php echo $this->getSkinUrl('images/text_tomorrow.png'); ?>);
            width:111px;
        }
        .christmas-product-list-feature .monday	.day-of-product-feature {
            background-image:url(<?php echo $this->getSkinUrl('images/text_monday.png'); ?>);

        }
        .christmas-product-list-feature .tuesday .day-of-product-feature {
            background-image:url(<?php echo $this->getSkinUrl('images/text_tuesday.png'); ?>);

        }
        .christmas-product-list-feature .wednesday .day-of-product-feature {
            background-image:url(<?php echo $this->getSkinUrl('images/text_wednesday.png'); ?>);

        }
        .christmas-product-list-feature .thursday .day-of-product-feature {
            background-image:url(<?php echo $this->getSkinUrl('images/text_thursday.png'); ?>);

        }
        .christmas-product-list-feature .friday	.day-of-product-feature {
            background-image:url(<?php echo $this->getSkinUrl('images/text_friday.png'); ?>);

        }
        .christmas-product-list-feature .saturday .day-of-product-feature {
            background-image:url(<?php echo $this->getSkinUrl('images/text_saturday.png'); ?>);

        }
        .christmas-product-list-feature .sunday	.day-of-product-feature {
            background-image:url(<?php echo $this->getSkinUrl('images/text_sunday.png'); ?>);

        }
    </style>
<?php } ?> <!--end check from date and to date -->
</div>
<a href="#christmas-promotion-popup" id="click-christmas-popup" style="display: none">click</a>
